# Generated by Django 3.2 on 2022-02-17 04:00

from django.db import migrations
from django.core.management import call_command


def populate_db(apps, schema_editor):
    call_command('loaddata', 'users.json')
    call_command('loaddata', 'meetings.json')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
